# Generated by Django 5.0.2 on 2024-02-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=200, unique=True, verbose_name='Nombre de usuario')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('password', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('foto_perfil', models.ImageField(default='avatar.png', upload_to='static/profile_pics', verbose_name='Foto de perfil')),
                ('esta_bloqueado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('foto_publicacion', models.ImageField(upload_to='static/imgs')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='libreria.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=400, verbose_name='Comentario')),
                ('fecha_publicacion_comentario', models.DateField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='libreria.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.usuario')),
            ],
        ),
    ]
