# Generated by Django 5.0.2 on 2024-02-21 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Nombre de usuario')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre completo')),
                ('profile_pic', models.ImageField(blank=True, default='media/avatar.png', upload_to='media/profile_pics', verbose_name='Foto de perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='users', to='libreria.group')),
                ('user_permissions', models.ManyToManyField(related_name='user_permissions_users', to='libreria.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_publicacion', models.ImageField(upload_to='publicaciones', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='libreria.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=400, verbose_name='Comentario')),
                ('fecha_publicacion_comentario', models.DateField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='libreria.publicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
