# Generated by Django 5.0.2 on 2024-02-26 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='libreria.publicacion'),
        ),
    ]
