# Generated by Django 5.0.2 on 2024-02-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_remove_perfil_full_name_alter_comentario_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_recurso', models.ImageField(upload_to='recursos', verbose_name='Archivo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha_publicacion_recurso', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'ordering': ['-fecha_publicacion_recurso'],
            },
        ),
    ]
