# Generated by Django 5.0.2 on 2024-02-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='archivo_recurso',
            field=models.FileField(upload_to='recursos', verbose_name='Archivo'),
        ),
    ]
