# Generated by Django 5.0.2 on 2024-02-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_recursos_archivo_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='nombre',
            field=models.CharField(default='Recursos', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='archivo_recurso',
            field=models.FileField(upload_to='media/recursos', verbose_name='Archivo'),
        ),
    ]
