# Generated by Django 5.0.2 on 2024-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_recursos_nombre_alter_recursos_archivo_recurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recursos',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='recursos',
            name='descripcion',
            field=models.CharField(max_length=400, verbose_name='Descripción'),
        ),
    ]
