# Generated by Django 5.0.2 on 2024-03-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0011_remove_publicacion_foto_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones', verbose_name='Imagen'),
        ),
    ]
