# Generated by Django 5.0.2 on 2024-03-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_actividad_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actividad',
        ),
    ]
