# Generated by Django 5.0.2 on 2024-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_remove_perfil_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
