# Generated by Django 5.0.2 on 2024-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_perfil_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iframe', models.TextField()),
            ],
        ),
    ]
