# Generated by Django 5.0.2 on 2024-03-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_iframe_descripcion_alter_iframe_codigo_iframe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframe',
            options={'ordering': ['-id']},
        ),
    ]
