# Generated by Django 5.0.2 on 2024-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_alter_iframe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframe',
            name='descripcion',
            field=models.CharField(max_length=400, verbose_name='Descripción'),
        ),
    ]
